import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect } from "react";
import { InferGetServerSidePropsType } from "next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const Home = ({ version }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  useEffect(() => {
    console.log("version 5");
  }, []);
  console.log("version 5 server");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ display: "flex", justifyContent: "center", alignItems: "center", height: "100vh" }}>
        <h1 style={{ color: "red", fontSize: "4rem", fontWeight: "bold" }}>Version: {version}</h1>
      </div>
    </>
  );
};
export default Home;
export async function getServerSideProps() {
  console.log("version 5 server");

  return {
    props: {
      version: "10",
    },
  };
}
